export type BriefingQuestion = { key: string; label: string }

export const generalBriefingQuestions: BriefingQuestion[] = [
  { key: "nomeEmpresa", label: "Nome da empresa" },
  { key: "telefoneContato", label: "Telefone de contato" },
  { key: "email", label: "Email" },
  { key: "whatsapp_numero", label: "Qual sera o numero do WhatsApp conectado na IA?" },
  { key: "endereco", label: "Endereco" },
  { key: "site", label: "Site" },
  { key: "redesSociais", label: "Redes sociais" },
  { key: "objetivoPrincipalIa", label: "Qual e o principal objetivo dessa IA?" },
  { key: "resultadoPerfeito", label: "O que seria um resultado perfeito pra voce?" },
  { key: "iaNaoPodeFazer", label: "O que a IA nao pode fazer de jeito nenhum?" },
  { key: "oQueVende", label: "O que voce vende exatamente?" },
  { key: "publicoIdeal", label: "Quem e seu publico ideal?" },
  { key: "doresPublico", label: "Quais sao as principais dores desse publico?" },
  { key: "diferencialEmpresa", label: "Qual e o diferencial da sua empresa hoje?" },
  { key: "tomDeVoz", label: "A IA deve ser mais formal ou mais descontraida?" },
  { key: "usoEmojis", label: "Pode usar emojis ou nao?" },
  { key: "nivelDetalhe", label: "Deve ser curta e direta ou mais explicativa?" },
  { key: "referenciasComunicacao", label: "Existe algum exemplo de comunicacao que voce gosta?" },
  { key: "perguntasObrigatorias", label: "Quais perguntas a IA precisa fazer obrigatoriamente?" },
  { key: "transferenciaHumano", label: "Em que momento deve transferir para humano?" },
  { key: "quemRecebeLead", label: "Quem recebe o lead depois?" },
  { key: "setoresTransferencia", label: "Existe mais de 1 setor? Se sim, informe os setores e quando cada um deve receber a transferencia." },
  { key: "assuntoProibido", label: "Existe algum assunto proibido?" },
  { key: "podeFalarPreco", label: "A IA pode falar preco?" },
  { key: "podeNegociar", label: "Pode negociar ou so apresentar?" },
  { key: "scriptsFixos", label: "Tem respostas que devem ser padrao (script fixo)?" },
  { key: "ofertasPrincipais", label: "Quais sao suas ofertas principais?" },
  { key: "promocoesAtivas", label: "Tem promocoes ou gatilhos de anuncios ativos que devem ser usados?" },
  { key: "objecoesMaisComuns", label: "Quais objecoes voce mais recebe hoje?" },
  { key: "comoFechaVenda", label: "Como voce costuma fechar uma venda?" },
  { key: "leadQualificado", label: "O que define um lead qualificado pra voce?" },
  { key: "informacoesObrigatorias", label: "Quais informacoes sao obrigatorias coletar?" },
  { key: "criteriosDescarte", label: "Existe algum criterio pra descartar leads?" },
  { key: "perguntasRepetidas", label: "Quais perguntas mais se repetem?" },
  { key: "ondePerdeLeads", label: "Onde voce perde mais leads hoje?" },
]

export const dealershipBriefingQuestions: BriefingQuestion[] = [
  { key: "nomeEmpresa", label: "Nome da empresa" },
  { key: "telefoneContato", label: "Telefone de contato" },
  { key: "email", label: "Email" },
  { key: "endereco", label: "Endereco" },
  { key: "site", label: "Site" },
  { key: "redesSociais", label: "Redes sociais" },
  { key: "funcionamento", label: "Dias e horarios de funcionamento" },
  { key: "quantidadeVendedores", label: "Quantos vendedores tem atualmente?" },
  { key: "vendedores", label: "Informe o nome e telefone de cada vendedor" },
  { key: "sistema_estoque", label: "Qual sistema de estoque sua loja utiliza?" },
  { key: "sistema_estoque_email", label: "Email de acesso" },
  { key: "sistema_estoque_senha", label: "Senha de acesso" },
  { key: "whatsapp_numero", label: "Qual sera o numero do WhatsApp conectado na IA?" },
  { key: "gerenteNotificacoes", label: "Nome e telefone do gerente que recebera as notificacoes da distribuicao de leads" },
  { key: "portaisAtivos", label: "Quais sao os portais que voces possuem?" },
  { key: "olxEmail", label: "Acesso ao OLX - Email" },
  { key: "olxSenha", label: "Acesso ao OLX - Senha" },
  { key: "outrosPortais", label: "Se marcou Outros, quais portais sao utilizados?" },
  { key: "gmailCanaisEmail", label: "Informe o acesso do e-mail que atualmente vocÃªs recebem os e-mails dos leads que chegam pelos canais de atendimento." },
  { key: "gmailCanaisSenha", label: "Senha" },
  { key: "confirmaEmailPortais", label: "VocÃª confirma que todos os e-mails que chegam nos portais de atendimento mencionados, chegam exatamente nesse e-mail cadastrado acima?" },
  { key: "pos_venda", label: "Quando um cliente comprador entrar em contato apos a compra, para qual pessoa ele deve ser transferido? (Ex: gerente, atendente especifico?)" },
  { key: "nome_sujo", label: "Qual deve ser a conduta da IA quando o lead informar que possui restricao no nome? (Ex: informar que nao e possivel financiar, oferecer apenas pagamento a vista, encerrar o atendimento, transferir para humano?)" },
  { key: "veiculo_fora_estoque", label: "Se o lead pedir um modelo que nao esta no estoque, a IA deve oferecer alternativas? Se sim, pode sugerir qualquer veiculo ou seguir algum criterio? Quando deve transferir para um vendedor?" },
  { key: "sinistro", label: "O que a IA deve dizer quando o lead perguntar sobre veiculos sinistrados ou mencionar sinistro?" },
  { key: "formas_pagamento", label: "Quais formas de pagamento sua loja aceita?" },
  { key: "formas_pagamento_outros", label: "Outras formas de pagamento" },
  { key: "distribuicaoLeads", label: "Como sera a distribuicao dos leads da sua loja?" },
  { key: "realizaAgendamentos", label: "Sua concessionaria realiza agendamentos?" },
  { key: "trabalhaRepasse", label: "Sua loja trabalha com repasse de veiculos?" },
  { key: "naoPodeFalar", label: "O que a IA nao pode falar de jeito nenhum?" },
  { key: "informacoesPermitidas", label: "Quais informacoes a IA pode informar ao lead?" },
  { key: "nomeIa", label: "Digite abaixo o nome que voce deseja que a IA se chame:" },
]
