export const taskTemplates = {
  "EAZYSALES (PROSPECTVENDAS)": [
    "CRIAR CONTA NA EAZYSALES",
    "CADASTRAR USUARIOS",
    "CONFIGURAR CRM",
    "IMPORTAR BASE DE CLIENTES ATIVOS JA COM A TAG :'CLIENTE_ATIVO'",
    "CONECTAR O FACEBOOK/INSTAGRAM",
    "RECEBER COPY FOLLOW UP PROPOSTA DO LEAD PARA CONFIGURAÇÃO NA EAZYSALES",
    "CRIAR TAREFAS QUANDO FOR MOVIMENTADO PARA A ETAPA FECHADO GANHO",
    "CRIAR TAREFAS QUANDO FOR MOVIMENTADO PARA A ETAPA PERDIDO",
    "CONECTAR O PORTIFOLIO EMPRESARIAL",
    "CONEXÃO WHATSAPP API OFICIAL",
    "CONFIGURAÇÃO DE EMAIL MKT",
    "CONFIGURAR GOOGLE ADS",
  ],
  "TAREFAS EAZYSTART": [
    "[D0] [BRIEFING] Enviar briefing para o cliente preencher",
    "[D0] [BRIEFING] Obter versão 1 do prompt (salvar com o documento)",
    "[D1] [ACOMPANHAMENTO] ACOMPANHAR COMO FUNCIONA O COMERCIAL DO CLIENTE",
    "[D1] [ACESSOS] Criação de Gmail do cliente",
    "[D1] [ACESSOS] Criação de conta no Supabase",
    "[D1] [ACESSOS] Criação de conta na OpenAI",
    "[D1] [ACESSOS] Criação da planilha de interações com leads",
    "[D0] [PÓS] Preencher descrição do grupo com logins e vídeos tutoriais",
    "[D2] [ESTRUTURA] Duplicar cenário N8N EazyStart",
    "[D2] [ESTRUTURA] Gerar credenciais e tokens",
    "[D2] [ESTRUTURA] Criar instância do Evolution",
    "[D2] [ESTRUTURA] Criar prompt da IA na OpenAI",
    "[D2] [ESTRUTURA] Conectar Google Sheets para cadastro de leads",
    "[D2] [ESTRUTURA] Conectar planilha de consulta (catálogo, se necessário)",
    "[D3] [PÓS] Informar início dos testes ao cliente",
    "[D4] [TESTES] Testar internamente a estrutura",
    "[D4] [TESTES] Testar com equipe diferentes interações",
    "[D5] [TESTES] Realizar teste final",
    "[D5] [PÓS] Informar finalização dos testes e marcar entrega",
    "[D6] [PÓS] Ativar IA do cliente",
    "[D7+] [PÓS] Validação e ajustes após 7 dias",
    "[D15+] [PÓS] Validação e coleta de feedback após 15 dias",
    "ADICIONAR LOGS DE ATUALIZAÇÃO NO GRUPO",
  ],
  "TAREFAS EAZY SALES (interno)": [
    "[ONBOARDING] - REUNIÃO DE CAPTURA DE ACESSOS",
    "[ONBOARDING] - CONECTAR FACEBOOK + INSTAGRAM COM O CLIENTE NA CALL VIA ANY DESK OU MEET",
    "[ONBOARDING] - CONEXÃO ZAPTOS ? - CRIAR CONTA ZAPTOS PARA ESCANEAR QR CODE VIA MEET",
    "[ONBOARDING] - CONEXÃO API OFICIAL ? - CONECTAR PORFOLIO EMPRESARIAL NA CONTA DO CLIENTE VIA MEET OU ANYDESK",
    "[ONBOARDING] - LEVAMENTO DE ESTÁGIOS CRM + PROCESSO DE AUTOMAÇÃO",
    "[ONBOARDING] - LEVANTAMENTO DE PESSOAS QUE TERÃO ACESSOS",
    "[ONBOARDING] - CRIAÇÃO DE CONTA DE CADA USUÁRIO DO SISTEMA COM AS DEVIDAS PERMISSÕES",
    "[ONBOARDING] - CONECTAR CARTÃO DE CRÉDITO",
    "[CRM] - CONFIGURAR PIPELINES E FUNIL",
    "[CRM] - AUTOMAÇÃO DE MOVIMENTAÇÃO DO CRM",
    "[AUTOMAÇÃO] - CRIAR AUTOMAÇÃO PARA ATENDIMENTO WHATSAPP",
    "[AUTOMAÇÃO] - CRIAR DISTRIBUIÇÃO DE ATENDIMENTO (SE TIVER)",
    "[AUTOMAÇÃO] - CRIAR AUTOMAÇÃO DE RESPOSTA DE COMENTÁRIO NA DM",
    "[AUTOMAÇÃO] - CRIAR AUTOMAÇÃO DE RESPOSTA AUTOMÁTICA NA DM",
    "[AUTOMAÇÃO] - FOLLOW UP VIA CRM",
    "[TESTES] - TESTAR TODO O PROCESSO + DE 5 VEZES PARA MAPEAR POSSIVEIS ERROS",
    "[ENTREGA] - MARCAR REUNIÃO DE ENTREGA",
    "[ENTREGA] - APLICAR TREINAMENTO",
    "[ACOMPANHAMENTO] - ACOMPANHAR TODO O O PROCESSO DURANTE 7 DIAS INTENSOS",
    "[FEEDBACK] - ACOMPANHAR COMO O PROJETO ESTÁ E SE ESTÁ ENFRENTANDO PROBLEMAS",
    "[AJUSTES] - AJUSTAR CASO NECESSÁRIO",
    "[FINALIZAÇÃO] - DAR CONCLUIDO NO PROJETO",
    "ADICIONAR LOGS DE ATUALIZAÇÃO NO GRUPO",
  ],
  "TAREFAS EAZY PRO": [
    "[D0] [BRIEFING] Enviar briefing ao cliente",
    "[D0] [BRIEFING] Obter versão 1 do prompt",
    "[D0] [KICK OFF] CONECTAR A UAZAPI",
    "[D0] [KICK OFF] CONFIGURAR A DATA DE ENTREGA DE TODAS AS TAREFAS DO PROJETO",
    "[D0] [KICK OFF] Criar instância do UAZAPI",
    "[D0] [KICK OFF] Pegar todos os acessos necessários para dar inicio ao Projeto",
    "[D0] [PÓS] Preencher descrição do grupo com dados e vídeos",
    "[D1] [ACESSOS] Criação de Gmail",
    "[D1] [ACESSOS] Criação de OpenAI",
    "[D1] [ACESSOS] Criação de projeto V0 / vs code",
    "[D1] [ACESSOS] Criação de Supabase",
    "[D15+] [PÓS] Validação final + feedback (15 dias)",
    "[D2] [ESTRUTURA] Criar CRM EazyCLICK / EAZY LEADS",
    "[D2] [ESTRUTURA] Criar prompt na OpenAI",
    "[D2] [ESTRUTURA] Duplicar cenário N8N EazyPro",
    "[D2] [ESTRUTURA] Gerar credenciais",
    "[D3] [ESTRUTURA] Configurar Follow-up",
    "[D3] [ESTRUTURA] Integração Supabase com CRM",
    "[D4] [PÓS] Informar cliente sobre início dos testes",
    "[D5] [TESTES] Teste interno completo com equipe (incluindo Follow-up)",
    "[D7] [PÓS] Informar cliente e agendar entrega",
    "[D7] [TESTES] Teste final",
    "[ESTRUTURA] CRIAR AUTOMAÇÕES DE AGENDAMENTO",
    "[ESTRUTURA] CRIAR Calendário Google",
    "[D7+] [PÓS] Ativar IA (UAZAPI)",
    "[D7+] [PÓS] Validação + ajustes (7 dias)",
    "ADICIONAR LOGS DE ATUALIZAÇÃO NO GRUPO",
  ],
  "TAREFAS EAZY PRO CONCESSIONARIA": [
    "[D0] [BRIEFING] Enviar briefing ao cliente",
    "[D0] [BRIEFING] Obter versão 1 do prompt",
    "[D0] [KICK OFF] CONECTAR A UAZAPI",
    "[D0] [KICK OFF] Criar instância do UAZAPI",
    "[D0] [KICK OFF] Pegar todos os acessos necessários para dar inicio ao Projeto",
    "[D0] [PÓS] Preencher descrição do grupo com dados e vídeos",
    "[D1] [ACESSOS] Criação de Gmail",
    "[D1] [ACESSOS] Criação de OpenAI",
    "[D1] [ACESSOS] Criação de projeto CRM",
    "[D1] [ACESSOS] Criação de Supabase",
    "[D15+] [PÓS] Validação final + feedback (15 dias)",
    "[D2] [ESTRUTURA] Criar CRM EazyLeads",
    "[D2] [ESTRUTURA] Criar prompt na OpenAI",
    "[D2] [ESTRUTURA] Duplicar cenário N8N EazyPro",
    "[D2] [ESTRUTURA] Gerar credenciais",
    "[D3] [ESTRUTURA] Configurar Follow-up",
    "[D3] [ESTRUTURA] Integração com o Revenda Mais ou AUTO CERTO",
    "[D3] [ESTRUTURA] Integração com os canais de aquisição de Leads (Só Carrão, Revenda Mais, WebMotors)",
    "[D3] [ESTRUTURA] Integração Supabase com CRM",
    "[D4] [PÓS] Informar cliente sobre início dos testes",
    "[D5] [TESTES] Teste interno completo com equipe (incluindo Follow-up)",
    "[D7] [PÓS] Informar cliente e agendar entrega",
    "[D7] [TESTES] Teste final",
    "[D7+] [PÓS] Ativar IA (UAZAPI)",
    "[D7+] [PÓS] Validação + ajustes (7 dias)",
    "Teste de conexão com plataformas de vendas (Mercado Livre / Só Carrão / Chaves na Mão)",
    "Bateria de testes do CRM (movimentação inclusão manual transferência botões e layout)",
    "Teste de bateria da Inteligência Artificial (prompt distribuição de leads e script)",
    "ADICIONAR LOGS DE ATUALIZAÇÃO NO GRUPO",
  ],
} as const

export type TaskTemplateName = keyof typeof taskTemplates
